In [1]:
from sklearn import linear_model
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [2]:
from sklearn.datasets import load_breast_cancer

In [3]:
cancer=load_breast_cancer()

In [7]:
cancer.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [12]:
cancer['data'].shape

(569, 30)

In [13]:
x=cancer['data']
y=cancer['target']

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
x_train,x_test,y_train,y_test=train_test_split(x,y)

In [17]:
x_train

array([[1.205e+01, 1.463e+01, 7.804e+01, ..., 6.548e-02, 2.747e-01,
        8.301e-02],
       [7.729e+00, 2.549e+01, 4.798e+01, ..., 0.000e+00, 3.058e-01,
        9.938e-02],
       [2.058e+01, 2.214e+01, 1.347e+02, ..., 1.920e-01, 2.909e-01,
        5.865e-02],
       ...,
       [1.221e+01, 1.802e+01, 7.831e+01, ..., 8.829e-02, 3.218e-01,
        7.470e-02],
       [2.094e+01, 2.356e+01, 1.389e+02, ..., 2.105e-01, 3.126e-01,
        7.849e-02],
       [1.230e+01, 1.902e+01, 7.788e+01, ..., 3.983e-02, 2.554e-01,
        7.207e-02]])

In [19]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)

StandardScaler()

In [20]:
x_train=scaler.transform(x_train)

In [21]:
x_test=scaler.transform(x_test)

In [22]:
x_train

array([[-0.5862157 , -1.10046992, -0.5680937 , ..., -0.7172292 ,
        -0.25854937, -0.01435812],
       [-1.81937148,  1.42857514, -1.81370959, ..., -1.69410098,
         0.23339623,  0.8966422 ],
       [ 1.84813256,  0.64843693,  1.77976379, ...,  1.17027565,
        -0.00229475, -1.37000673],
       ...,
       [-0.54055383, -0.31101663, -0.55690554, ..., -0.37693529,
         0.48648721, -0.4768146 ],
       [ 1.95087176,  0.97912238,  1.95380194, ...,  1.44627028,
         0.3409599 , -0.26589883],
       [-0.51486903, -0.07813955, -0.57472373, ..., -1.09989202,
        -0.56384037, -0.62317568]])

In [23]:
from sklearn.neural_network import MLPClassifier

In [24]:
mlp=MLPClassifier(hidden_layer_sizes=(30,30,30))

In [25]:
mlp.fit(x_train,y_train)

MLPClassifier(hidden_layer_sizes=(30, 30, 30))

In [26]:
y_predict=mlp.predict(x_test)
y_predict

array([0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0])

In [27]:
y_test

array([0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0])

In [28]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [29]:
accuracy_score(y_predict,y_test)

0.958041958041958

In [30]:
confusion_matrix(y_predict,y_test)

array([[49,  1],
       [ 5, 88]])